import type { FuelType, NewsEvent } from './types'

const all = (mul: number): Partial<Record<FuelType, number>> => ({ a92: mul, a95: mul, diesel: mul })
const gas = (mul: number): Partial<Record<FuelType, number>> => ({ a92: mul, a95: mul })

export const NEWS_POOL: NewsEvent[] = [
  {
    id: 'market-up-01',
    category: 'market-up',
    source: 'ТСН: економіка',
    headline: 'ЕКСКЛЮЗИВ: Нафтогаз забув ціну А-95 у Малинівці - після 18:00 літр рахує калькулятор із ЖЕКу',
    body: 'У Малинівці вирішили рахувати літри вручну, а до вечора обіцяли повернутися до калькулятора. Оптовики потирають руки.',
    effects: { priceMul: all(1.18), demandMul: all(1.12) },
    durationTicks: 48,
    weight: 4,
  },
  {
    id: 'market-up-02',
    category: 'market-up',
    source: 'ТСН: надзвичайні ціни',
    headline: 'Надзвичайні новини: 130-літровий МТЗ у Решетилівці з’їв дизель і попросив добавку',
    body: 'Тракторист Панас залив усі 130 літрів і зізнався: «ще трохи - і поїхав би на дизелі додому». ДП у регіоні стрибнув.',
    effects: { priceMul: { diesel: 1.27 }, demandMul: { diesel: 1.2 } },
    durationTicks: 54,
    weight: 3,
  },
  {
    id: 'market-up-03',
    category: 'market-up',
    source: 'ТСН: розслідування',
    headline: 'ТСН розслідує: таксисти на 17 Октавіях з Борисполя одночасно поїхали за А-95',
    body: 'Колона таксі простягнулася від Борисполя до обласного центру. Диспетчери кажуть: «краще А-95, ніж без роботи».',
    effects: { priceMul: { a92: 1.2, a95: 1.22 }, demandMul: { a92: 1.14, a95: 1.16 } },
    durationTicks: 42,
    weight: 5,
  },
  {
    id: 'market-up-04',
    category: 'market-up',
    source: 'ТСН: аграрні новини',
    headline: 'ТСН розслідує: 9 комбайнів із Диканьки вийшли в поле - ДП стривожено дивиться на резервуари',
    body: 'Комбайни виїхали в поле і одразу ж повернулися на заправку. Аграрії просять у неба дизель, у землі - врожай.',
    effects: { priceMul: { diesel: 1.35 }, demandMul: { diesel: 1.25 } },
    durationTicks: 60,
    weight: 2,
  },
  {
    id: 'market-up-05',
    category: 'market-up',
    source: 'ТСН: міжнародна паніка',
    headline: 'Надзвичайні новини: ОПЕК назвав 48 ₴ «тимчасово» - у Калинівці це вже третій тиждень',
    body: 'Слово «тимчасово» в ОПЕК тримається вже третій тиждень. В Україні до нього ставляться з розумінням і повним баком.',
    effects: { priceMul: all(1.15), demandMul: all(1.1) },
    durationTicks: 36,
    weight: 6,
  },
  {
    id: 'market-up-06',
    category: 'market-up',
    source: 'ТСН: транспорт',
    headline: 'ТСН розслідує: 12 таксистів із Черкас взяли А-92 «до бабці» - бабця зникла з маршруту',
    body: 'Бабця виявилася в сусідньому районі. Таксисти клянуться, що назад приїдуть теж із повним баком.',
    effects: { priceMul: gas(1.3), demandMul: gas(1.18) },
    durationTicks: 66,
    weight: 4,
  },
  {
    id: 'market-up-07',
    category: 'market-up',
    source: 'ТСН: село та ціни',
    headline: 'ЕКСКЛЮЗИВ: МТЗ-тракторист із Баришівки за 65 л ДП отримав чек довший за город',
    body: 'Чек на 65 літрів дизелю зберігають у рамці. Город горить, трактор їде.',
    effects: { priceMul: { diesel: 1.4 }, demandMul: { diesel: 1.3 } },
    durationTicks: 72,
    weight: 2,
  },
  {
    id: 'market-up-08',
    category: 'market-up',
    source: 'ТСН: парламентський блок',
    headline: 'Надзвичайні новини: Рада о 23:00 обговорила 51 ₴ - і вирішила додати ще одну комісію',
    body: 'Комісія з питань пального створила підкомісію. Підкомісія пообіцяла розібратися до наступного подорожчання.',
    effects: { priceMul: all(1.2), demandMul: all(1.14) },
    durationTicks: 50,
    weight: 5,
  },
  {
    id: 'market-down-01',
    category: 'market-down',
    source: 'ТСН: добрі новини',
    headline: 'ЕКСКЛЮЗИВ: На 9-й заправці Малинівки знайшли А-92 дешевше - ціна впала «після свят»',
    body: 'Свята закінчилися ще навесні, але ціна впала щойно. Продавці дивуються не менше за покупців.',
    effects: { priceMul: all(0.88), demandMul: all(0.92) },
    durationTicks: 45,
    weight: 5,
  },
  {
    id: 'market-down-02',
    category: 'market-down',
    source: 'ТСН: комунальний скандал',
    headline: 'ТСН розслідує: ЖЕК у Ніжині переплутав труби й випадково здешевив 1 000 л ДП',
    body: 'Замість води в кранах - дизель за акцією. ЖЕК вибачається і просить не палити поблизу.',
    effects: { priceMul: { diesel: 0.82 }, demandMul: { diesel: 0.85 } },
    durationTicks: 55,
    weight: 3,
  },
  {
    id: 'market-down-03',
    category: 'market-down',
    source: 'ТСН: полтавський випуск',
    headline: 'Надзвичайні новини: 3 бензовози в Полтаві повернулися порожні - водії «зайшли до бабці»',
    body: 'Водії зайшли «на п’ять хвилин» і вийшли через дві доби. Пальне в місті подешевшало від подиву.',
    effects: { priceMul: gas(0.9), demandMul: gas(0.95) },
    durationTicks: 38,
    weight: 4,
  },
  {
    id: 'market-down-04',
    category: 'market-down',
    source: 'ТСН: аграрний блок',
    headline: 'ЕКСКЛЮЗИВ: ДП по 53 ₴ оголосили «дорогим» - фермер у Гадячі замовив ще 2 каністри',
    body: 'Фермер пояснив: «аби дорожчало не так швидко». Логіку зрозуміли не всі, але каністри розкупили.',
    effects: { priceMul: { diesel: 0.84 }, demandMul: { diesel: 0.88 } },
    durationTicks: 62,
    weight: 2,
  },
  {
    id: 'market-down-05',
    category: 'market-down',
    source: 'ТСН: Держспоживслужба',
    headline: 'Надзвичайні новини: на 7-й АЗС Чернігова дешевший ДП пояснили словом «після свят»',
    body: 'Слово «після свят» тепер офіційне пояснення будь-якої ціни. Економісти знизали плечима й порахували вигоду.',
    effects: { priceMul: all(0.93), demandMul: all(0.96) },
    durationTicks: 34,
    weight: 6,
  },
  {
    id: 'demand-01',
    category: 'demand',
    source: 'ТСН: дорожній рух',
    headline: 'ЕКСКЛЮЗИВ: 14 водіїв із Миргорода почули «знижка» - і влаштували чергу ще до сніданку',
    body: 'Слово «знижка» почули у трьох сусідніх селах. Черга зайняла місце ще до відкриття.',
    effects: { demandMul: all(1.55) },
    durationTicks: 28,
    weight: 7,
  },
  {
    id: 'demand-02',
    category: 'demand',
    source: 'ТСН: весільний випуск',
    headline: 'Надзвичайні новини: весілля на 200 людей у Полтаві стартувало з черги за А-92',
    body: 'Молодята поїхали заправлятися ще до ЗАГСу. Свахи кажуть: без повного бака весілля не весілля.',
    effects: { demandMul: gas(1.7) },
    durationTicks: 32,
    weight: 6,
  },
  {
    id: 'demand-03',
    category: 'demand',
    source: 'ТСН: розслідування',
    headline: 'ТСН розслідує: у Малинівці 27 таксистів сказали «тільки А-95» - пасажири пішли пішки',
    body: 'На питання «чому не газ?» таксисти відповіли двигателем. Пасажири дійшли пішки, але з гідністю.',
    effects: { demandMul: gas(1.85) },
    durationTicks: 40,
    weight: 4,
  },
  {
    id: 'demand-04',
    category: 'demand',
    source: 'ТСН: спеціальний репортаж',
    headline: 'Надзвичайні новини: 5 фур із Хорола зупинились «буквально на хвилинку» - черга вже спить',
    body: 'Хвилинка триває другу годину. Водії фур п’ють каву і бережуть чергу одночасно.',
    effects: { demandMul: { diesel: 1.45 } },
    durationTicks: 36,
    weight: 6,
  },
  {
    id: 'demand-05',
    category: 'demand',
    source: 'ТСН: ранковий ефір',
    headline: 'Надзвичайні новини: 6 автобусів із Пирятина одночасно згадали, що завтра понеділок',
    body: 'Автобуси згадали про понеділок усі разом - неділя так і не склалася.',
    effects: { demandMul: all(1.35) },
    durationTicks: 24,
    weight: 8,
  },
  {
    id: 'demand-06',
    category: 'demand',
    source: 'ТСН: пенсійний блок',
    headline: 'ТСН розслідує: після телевізора 19 пенсіонерів із Кременчука купили А-95 «бо так сказали»',
    body: 'Дід Панас записався в чергу одразу після прогнозу погоди. Баба Параска - за ним, із бутербродами.',
    effects: { demandMul: gas(1.6) },
    durationTicks: 52,
    weight: 5,
  },
  {
    id: 'demand-07',
    category: 'demand',
    source: 'ТСН: базарний випуск',
    headline: 'ЕКСКЛЮЗИВ: 8 машин із Хорола повернулися з базару - водії згадали про повний бак',
    body: 'Поверталися з базару порожні - окрім баків. Тепер повні і бак, і багажник.',
    effects: { demandMul: all(1.25) },
    durationTicks: 44,
    weight: 8,
  },
  {
    id: 'demand-08',
    category: 'demand',
    source: 'ТСН: весільна рубрика',
    headline: 'Надзвичайні новини: 31 літр А-92 став головною покупкою весілля у Решетилівці',
    body: 'Наречений визнав: «квіти зав’януть, а бак - ні». Свекруха погодилася не одразу.',
    effects: { demandMul: gas(1.5) },
    durationTicks: 58,
    weight: 4,
  },
  {
    id: 'demand-09',
    category: 'demand',
    source: 'ТСН: тракторний блок',
    headline: 'ТСН розслідує: 5 МТЗ із Глобиного приїхали разом - хтось сказав «дизель»',
    body: 'Хтось крикнув «дизель» - і всі п’ять поїхали. Трактори попереду, логіка позаду.',
    effects: { demandMul: { diesel: 1.4 } },
    durationTicks: 30,
    weight: 7,
  },
  {
    id: 'operational-01',
    category: 'operational',
    source: 'ТСН: події на АЗС',
    headline: 'ЕКСКЛЮЗИВ: насос №2 на АЗС «Трембіта» образився на 200-літрову каністру',
    body: 'Насос №2 відмовився працювати з 200-літровою каністрою: «я не бензовоз», мовляв. Профілактика - 20 хвилин.',
    effects: { pumpOutTicks: 20 },
    durationTicks: 20,
    weight: 8,
  },
  {
    id: 'operational-02',
    category: 'operational',
    source: 'ТСН: комунальний ефір',
    headline: 'ТСН розслідує: насос №4 у Калинівці просить 15 хвилин тиші - причина «профілактика»',
    body: 'Технік каже: насос просто втомився. П’ятнадцять хвилин тиші прописали офіційно.',
    effects: { pumpOutTicks: 26 },
    durationTicks: 26,
    weight: 6,
  },
  {
    id: 'operational-03',
    category: 'operational',
    source: 'ТСН: місцеві новини',
    headline: 'ЕКСКЛЮЗИВ: ЖЕК Зінькова о 07:30 перекрив під’їзд до колонки №3',
    body: 'Ремонт труби «ще з минулого року» нарешті почався. Під’їзд відкриють, коли скінчиться профілактика.',
    effects: { pumpOutTicks: 34 },
    durationTicks: 34,
    weight: 4,
  },
  {
    id: 'operational-04',
    category: 'operational',
    source: 'ТСН: надзвичайні події',
    headline: 'Надзвичайні новини: насос №6 побачив чек на 80 л у Ніжині й узяв вихідний',
    body: 'Насос побачив чек на 80 літрів і зрозумів: йому теж потрібен відпочинок. Повернеться за 20 хвилин.',
    effects: { pumpOutTicks: 20 },
    durationTicks: 20,
    weight: 7,
  },
  {
    id: 'vip-01',
    category: 'vip',
    source: 'ТСН: світські новини',
    headline: 'ЕКСКЛЮЗИВ: голова ОПЕК приїхав у Гадяч - 9 важливих авто раптом захотіли А-92',
    body: 'Голова ОПЕК приїхав до Гадяча «просто в гості». Дев’ять важливих авто одразу згадали про повний бак.',
    effects: { priceMul: all(1.1), demandMul: all(1.2), vipWalletMul: 2.5 },
    durationTicks: 46,
    weight: 3,
  },
  {
    id: 'vip-02',
    category: 'vip',
    source: 'ТСН: особливий гість',
    headline: 'ТСН розслідує: 11 важливих гостей із Полтави замовили А-95, як на весілля на 200 людей',
    body: 'Гості замовили А-95 із розмахом весілля на 200 людей. Дехто з них - ще й із каністрами.',
    effects: { priceMul: gas(1.12), demandMul: gas(1.35), vipWalletMul: 2 },
    durationTicks: 54,
    weight: 5,
  },
  {
    id: 'vip-03',
    category: 'vip',
    source: 'ТСН: ексклюзив',
    headline: 'Надзвичайні новини: 42 водії з Кременчука побачили табличку «нема здачі» - і взяли більше А-95',
    body: 'Табличка «нема здачі» подіяла краще за будь-яку знижку. Водії беруть більше - «аби не рахувати».',
    effects: { priceMul: gas(1.08), demandMul: gas(1.28), vipWalletMul: 2 },
    durationTicks: 38,
    weight: 4,
  },
  {
    id: 'vip-04',
    category: 'vip',
    source: 'ТСН: аграрний ексклюзив',
    headline: 'ЕКСКЛЮЗИВ: 7 МТЗ із Лубен зустріли важливий фургон - ДП пішов галопом',
    body: 'Важливий фургон і сім МТЗ - це вже не черга, а парад. Дизель пішов галопом.',
    effects: { priceMul: { diesel: 1.16 }, demandMul: { diesel: 1.3 }, vipWalletMul: 3 },
    durationTicks: 60,
    weight: 3,
  },
  {
    id: 'crisis-01',
    category: 'crisis',
    source: 'ТСН: надзвичайні новини',
    headline: 'ЕКСКЛЮЗИВ: Трамп вторгся в Іран - барель підскочив, грн впав, дід Панас уже в черзі з трьома каністрами',
    body: 'Барель підскочив, гривня впала, дід Панас - уже в черзі. ТСН тримає руку на пульсі - і на бензоколонці.',
    effects: { priceMul: all(2.2), demandMul: all(1.8) },
    durationTicks: 60,
    weight: 1,
  },
  {
    id: 'crisis-02',
    category: 'crisis',
    source: 'ТСН: міжнародний огляд',
    headline: 'Надзвичайні новини: ОПЕК назавжди посварилася - кожен міністр сказав «хай подорожчає», але кожен про своє',
    body: 'Кожен міністр сказав «хай подорожчає», але кожен про своє. Нафтотрейдери вже потирають руки.',
    effects: { priceMul: all(1.9), demandMul: all(1.5) },
    durationTicks: 72,
    weight: 2,
  },
  {
    id: 'crisis-03',
    category: 'crisis',
    source: 'ТСН розслідує',
    headline: 'ТСН розслідує: паніка в Малинівці - заливають три баки, «а раптом Трамп і до нас»',
    body: 'Малинівка заливає три баки одночасно. На питання «навіщо три» відповідають: «а раптом Трамп і до нас».',
    effects: { priceMul: all(1.5), demandMul: all(2) },
    durationTicks: 45,
    weight: 2,
  },
]
